### ISSUE TITLE
팀원 역할 분담

### ISSUE THREAD

**Issue by kbs-kbs** [kbs-kbs/2024-OSS-Group-Project#10]
## 논의 목적
- 역할 분담

## 논의 내용
- 다음 8개의 파일 중 자신이 작성할 파일을 2개씩 골라서 댓글로 알려주세요. 선착순입니다.
  - 5, 6, 7번의 주제는 자신이 리뷰하고 싶은 오픈소스가 있다면 변경해도 됩니다.
  - 8번 파일은 5, 6, 7번 파일을 모아서 붙여넣고 보고서의 결론과 제언을 작성해주시면 됩니다.
  - README.md와 Wiki는 제가 작성할 예정입니다.

1. '01. 오픈소스소프트웨어 개요.md'
2. '02. 오픈소스 개발 도구와 환경 설정.md'
3. '03. 깃허브 프로젝트 기여 방법.md'
4. '04. 깃허브 프로젝트 생성 및 관리.md'
5. '깃허브 프로젝트 TensorFlow 분석.md (주제 변경 가능)'
6. '깃허브 프로젝트 React 분석.md (주제 변경 가능)'
7. '깃허브 프로젝트 Linux Kernel 분석.md (주제 변경 가능)'
8. '05. 여러 깃허브 프로젝트 분석 및 제언'

## 논의 마감
11월 23일까지

### 팀 과제 안내: 다음 내용과 디자인, 팀원들의 협업 활동을 함께 평가[^1]
- 내용과 함께 깃허브의 다양한 기능 사용 평가
  - 이슈, 마일스톤, 레이블, PR, 위키, 프로젝트 등
- 팀(수업의 같은 반 4-7명) 별 GitHub 저장소 구축
  - 내용 파일은.md 파일로 작성
  - 팀원의 활동이 축적
- 팀 과제 주소 업로드
  - [A반](https://docs.google.com/spreadsheets/d/1h9_Mlgt9wpgLoEXxeexH0rVLXnje0cYH-NCQoqE1eXg/edit?usp=sharing)
  - [B반](https://docs.google.com/spreadsheets/d/1N_nsCXXCHMTXm5z-7ULzgeUfiKECTVSyBsfPgSHF98I/edit?usp=sharing)
- 과제 마감일
  - 2024.12.06(금)
> - 사례1: 오픈소스소프트웨어 보고서 구축
>   - OSS 개요, OSS 역사
>   - 대표적 OSS 소개
>   - OSS 저작권
> - 사례2: 실제 소프트웨어 개발 구축
>   - ChatGPT로 최초 소프트웨어를 생성
>   - 팀원들이 더욱 개선해 나가는 협업 과정(커밋이 여러 번 발생)

[^1]: https://github.com/ai7dnn/2024-OSS

**Comment by jungsh20241509** [comment]
제가 1번하고 3번 하겠습니다

**Comment by MoonHwitae** [comment]
저는 2번,4번 하겠습니당

**Comment by sjunc** [comment]
5, 6 번 하겠습니다

**Comment by pcw11** [comment]
그럼 7, 8번은 제가 하겠습니다
