### ISSUE TITLE
01. 오픈소스소프트웨어 개요.md 초안 작성

### ISSUE THREAD

**Issue by kbs-kbs** [kbs-kbs/2024-OSS-Group-Project#13]
## 요약
'01. 오픈소스소프트웨어 개요.md' 초안 작성

## 작업자
<kbd>jungsh20241509</kbd>

## 작업 기한
11월 27일까지

## 작업 브랜치
<kbd>main</kbd>

## 작업 내용
1. 포크해 온 저장소에서 <kbd>🔄 Sync fork</kbd> 버튼 누르기
2. 포크해 온 저장소의 01. 오픈소스소프트웨어 개요.md 파일 작성

## 참고 사항
1. [오소소 위키 - 협업 규칙/소개](https://github.com/kbs-kbs/2024-OSS-Group-Project/wiki/%ED%98%91%EC%97%85-%EA%B7%9C%EC%B9%99#%EC%86%8C%EA%B0%9C)
2. [오소소 위키 - 협업 규칙/기여 파이프라인](https://github.com/kbs-kbs/2024-OSS-Group-Project/wiki/%ED%98%91%EC%97%85-%EA%B7%9C%EC%B9%99#%EA%B8%B0%EC%97%AC-%ED%8C%8C%EC%9D%B4%ED%94%84%EB%9D%BC%EC%9D%B8)

**Comment by jungsh20241509** [comment]
오픈소스 소프트웨어 개요
1.소스 코드 공개:사용자가 소프트웨어의 내부 동작을 이해할 수 있도록 소스 코드가 공개됩니다.또 개발자는 이를 분석하거나 수정하여 새로운 기능을 추가할 수 있습니다.
2.자유로운 사용과 배포:대부분의 오픈소스는 라이선스 조건에 따라 누구나 자유롭게 사용할 수 있습니다.또 개인 및 기업 모두 비용 없이 사용할 수 있는 경우가 많습니다.
3.커뮤니티 중심 개발:오픈소스는 전 세계가 개발자 커뮤니티의 협업을 통해 지속적으로 발전합니다.
장점
비용 절감;무료로 제공되는 경우가 많아 초기 비용이 낮음
투명성:코드가 공개되어 보안 취약점을 쉽게 파악 가능
커뮤니티 지원:문제 발생 시 많은 개발자들의 도움을 받을 수 있음
유연성:사용자 요구에 맞게 소프트웨어를 변경 가능
단점
기술적 지원 부족:상용 소프트웨어와 달리 공식적인 고객 지원이 부족 할 수 있음
학습 곡선: 복잡한 소프트웨어는 사용법이나 커스터마이징이 어려울 수 있음
품질 관리 어려움:누구나 기여할 수 있어 품질이 일관되지 않을 가능성

**Comment by kbs-kbs** [comment]
@jungsh20241509

좋습니다. 근데 댓글로 올리실 필요없이 저번 이미지 올려주셨을 때처럼 포크한 저장소의 '01. 오픈소스소프트웨어 개요.md' 라는 파일에 들어가셔서 <kbd>✏️</kbd> 버튼 누르고 올려주신 내용을 붙여넣으신 다음, 풀 리퀘스트 해주시면 됩니다.
