### ISSUE TITLE
02. 오픈소스 개발 도구와 환경 설정.md 초안 작성

### ISSUE THREAD

**Issue by kbs-kbs** [kbs-kbs/2024-OSS-Group-Project#14]
## 요약
'02. 오픈소스 개발 도구와 환경 설정.md' 초안 작성

## 작업자
<kbd>MoonHwitae</kbd>

## 작업 기한
11월 27일까지

## 작업 브랜치
<kbd>main</kbd>

## 작업 내용
1. 포크해 온 저장소에서 <kbd>🔄 Sync fork</kbd> 버튼 누르기
2. 포크해 온 저장소의 02. 오픈소스소프트웨어 개요.md 파일 작성

## 참고 사항
1. [오소소 위키 - 협업 규칙/소개](https://github.com/kbs-kbs/2024-OSS-Group-Project/wiki/%ED%98%91%EC%97%85-%EA%B7%9C%EC%B9%99#%EC%86%8C%EA%B0%9C)
2. [오소소 위키 - 협업 규칙/기여 파이프라인](https://github.com/kbs-kbs/2024-OSS-Group-Project/wiki/%ED%98%91%EC%97%85-%EA%B7%9C%EC%B9%99#%EA%B8%B0%EC%97%AC-%ED%8C%8C%EC%9D%B4%ED%94%84%EB%9D%BC%EC%9D%B8)

**Comment by MoonHwitae** [comment]
1.오픈소스 개발 도구
필수 도구 소개:
 ● 버전 관리 시스템:
   ● Git : 소스 코드 버전 관리를 위한 도구, 협업과 변경 이력 관리의 핵심.
   ● GitHub/GitLab/Bitbucket : 원격 저장소 및 협업 플랫폼.
 ● 코드 편집기 및 통합 개발 환경(IDE) :
   ● Visual Studio Code : 오픈소스 프로젝트에 최적화된 가볍고 강력한 편집기.
   ● IntelliJ IDEA PyCharm : 고급 IDE로 언어별 기능 제공.
 ● 패키지 관리자 :
   ● npm, Yarn ( Node.js용) : 자바스크립트 패키지 관리.
   ● pip (Python용) : 파이썬 패키지 설치 및 관리.
   ● Maven, Gradle (Java용) : 빌드 도구와 의존성 관리.
 ● 컨테이너와 가상화 도구 :
    ● Docker : 개발 환경을 컨테이너로 통일해 배포 및 테스트를 단순화.
   ● Vagrant : 개발용 가상 머신 설정 자동화.
보조 도구 :
 ● 디버깅 도구 :
   ● 브라우저 개발자 도구 (Chrome DevTools) : 웹 디버깅.
   ● Postman : API 테스트.
   ● GDB : C/C++ 디버깅.
   ● 테스트 및 품질 관리 도구:
   ● Jest, Pytest, JUnit : 단위 테스트.
   ● SonarQube : 코드 품질 분석.

2.개발 환경 설정
기본 설정 :
 ● 운영체제 선택 :
   ● Windows: WSL(Windows Subsystem for Linux)로 Linux 호환성 제공.
   ● macOS: UNIX 기반으로 개발 환경에 적합.
   ● Linux: 네이티브 개발 환경. Ubuntu, Fedora 추천.
 ● 필수 소프트웨어 설치 :
   ● Git, Node.js, Python 등 주요 개발 도구.
   ● IDE 및 에디터 플러그인 설치.
개발 환경 자동화 :
 ● 스크립트 작성 :
   ● Shell, Bash 스크립트를 사용해 초기화 작업 자동화.
   ● 예: git clone, 의존성 설치, 환경 변수 설정.
 ● 가상 환경 구성 :
   ● Python의 venv, JavaScript의 nvm 등을 이용한 환경 격리.

3.프로젝트 협업 및 관리
 ● Git 워크플로우 :
   ● 브랜치 전략(Git Flow, GitHub Flow)으로 작업 분리.
   ● Pull Request(PR) 생성 및 코드 리뷰 프로세스.
 ● Issue 및 작업 관리 :
   ● GitHub Issues, Project Boards로 작업 추적.
   ● Kanban 방식으로 작업 흐름 관리.
 ● CI/CD 파이프라인 구축 :
   ● GitHub Actions, Jenkins, Travis CI로 테스트 및 배포 자동화.

4.보안 및 유지보수
 ● 의존성 보안 관리 :
   ● Snyk, Dependabot로 취약점 점검 및 업데이트 알림.
 ● 환경 변수 관리 :
   ● .env 파일 사용 및 민감한 정보 보호.
 ● 리소스 최적화 :
   ● Docker 컨테이너 크기 최소화 및 캐싱 전략 활용.

5.Best Practices
 ● 효율적인 협업 :
   ● 코드 스타일 일관성을 위한 도구 사용 (ESLint, Prettier).
   ● 커밋 메시지 규칙 준수 (예: Conventional Commits).
 ● 문서화 :
   ● Markdown 기반 README 작성.
   ● 프로젝트 구조와 작업 프로세스 설명 포함.
 ● 테스트와 코드 품질 관리 :
   ● 정기적인 테스트 수해와 코드 리뷰.

**Comment by kbs-kbs** [comment]
@MoonHwitae

좋습니다. 근데 댓글로 올리실 필요없이 저번 이미지 올려주셨을 때처럼 포크한 저장소의 '02. 오픈소스소프트웨어 개요.md' 라는 파일에 들어가셔서 <kbd>✏️</kbd> 버튼 누르고 올려주신 내용을 붙여넣으신 다음, 풀 리퀘스트 해주시면 됩니다.

추가적으로 풀 리퀘스트 하시기 전에 내용을 마크다운 문법으로 바꿔주시면 좋은데,

1. `1.오픈소스 개발 도구` -> `## 1.오픈소스 개발 도구`
2. `필수 도구 소개:` -> `### 필수 도구 소개:`
3. `●` -> `-`

이런 식으로 다 바꿔주시면 됩니다. 그러면 사이트에서 볼 때 아래처럼 정리가 되서 보여집니다.

## 1.오픈소스 개발 도구
### 필수 도구 소개:
- 버전 관리 시스템:
  - Git : 소스 코드 버전 관리를 위한 도구, 협업과 변경 이력 관리의 핵심.
  - GitHub/GitLab/Bitbucket : 원격 저장소 및 협업 플랫폼.
