### ISSUE TITLE
03. 깃허브 프로젝트 기여 방법.md 초안 작성

### ISSUE THREAD

**Issue by kbs-kbs** [kbs-kbs/2024-OSS-Group-Project#15]
## 요약
'03. 깃허브 프로젝트 기여 방법.md' 초안 작성

## 작업자
<kbd>jungsh20241509</kbd>

## 작업 기한
11월 27일까지

## 작업 브랜치
<kbd>main</kbd>

## 작업 내용
1. 포크해 온 저장소에서 <kbd>🔄 Sync fork</kbd> 버튼 누르기
2. 포크해 온 저장소의 03. 깃허브 프로젝트 기여 방법.md 파일 작성

## 참고 사항
1. [오소소 위키 - 협업 규칙/소개](https://github.com/kbs-kbs/2024-OSS-Group-Project/wiki/%ED%98%91%EC%97%85-%EA%B7%9C%EC%B9%99#%EC%86%8C%EA%B0%9C)
2. [오소소 위키 - 협업 규칙/기여 파이프라인](https://github.com/kbs-kbs/2024-OSS-Group-Project/wiki/%ED%98%91%EC%97%85-%EA%B7%9C%EC%B9%99#%EA%B8%B0%EC%97%AC-%ED%8C%8C%EC%9D%B4%ED%94%84%EB%9D%BC%EC%9D%B8)

**Comment by jungsh20241509** [comment]
깃허브 프로젝트 기여 방법
1.프로젝트 찾기
1-1.적합한 프로젝트 찾기:관심 있는 주제나 기술 스택과 관련된 프로젝트를 선택하세요.
1-2.프로젝트 분석:CONTRIBUTING.m: 기여자를 위한 지침서. 수정 사항 제안 방법, 코드 스타일 규칙 등이 포함.Issues: 프로젝트에서 필요한 작업과 문제점 목록.
2.프로젝트 클론 및 환경 설정
2-1.저장소 포크(Fork):프로젝트의 GitHub 페이지에서 Fork 버튼을 클릭하여 자신의 계정으로 프로젝트를 복사합니다.
2-2.로컬 복제(Clone):포크한 저장소를 로컬로 복제합니다.
2-3.Branch 생성:새로운 브랜치를 만들어 작업 환경을 분리합니다.
3.문제 해결 또는 기능 개발
3-1.문제 이해:프로젝트의 Issues 섹션에서 해결할 작업을 선택합니다.
이해가 않는 부분은 댓글로 질문하여 명확히 합니다.
3-2.코드 작성:로컬 환경에서 코드를 수정하거나 새 기능을 추가합니다.
코드 스타일과 기여 지침(CONTRIBUTING.md)을 반드시 따릅니다.
3-3.변경 사항 확인:작성한 코드가 잘 작동하는지 확인합니다.
4.변경 사항 커밋 및 푸시
4-1.변경 사항 스테이징: 변경된 파일을 스테이지에 추가
4-2.커밋 메시지 작성:명확하고 간결한 메시지를 작성
4-3.원격 저장소로 푸시:변경 사항을 포크한 저장소로 푸시
5.Pull Request(Pull 요청) 생성
5-1.github 페이지에서 Pull Request 버튼을 클립합니다.
5-2.변경 내용을 설명하는 제목과 상세 설명을 작성합니다.
5-3.프로젝트 관리자가 PR을 검토하고 피드백을 제공합니다.
5-4.피드백에 따라 추가 수정이 필요할 수 있습니다.
6.리뷰 및 병합
6-1.관리자가 변경 사항을 승인하면 PR이 병합됩니다.
6-2.기여가 완료되면 원래 프로젝트 저장소의 업데이트 사항을 동기화합니다.
효과적인 기여를 위한 팁
1.작은 기여부터 시작:오타 수정,문서 개선 등 간단한 작업으로 익숙해지세요.
2.커뮤니케이션.PR이나 Issue에 질문하거나 의견을 남길 때는 정중하게 표현하세요.
3.커뮤니티 참여:프로젝트의 Slack,Discord 등을 활용해 더 깊이 참여하세요.
