### ISSUE TITLE
팀 과제 주제 선정

### ISSUE THREAD

**Issue by kbs-kbs** [kbs-kbs/2024-OSS-Group-Project#2]
## 논의 목적
- 팀 과제 주제 선정
## 논의 내용
- 팀 과제 안내의 '사례1' 또는 '사례2'를 참고해서 하고 싶은 주제를 댓글로 알려주세요.
  - 예시: 파이썬 라이브러리 만들기 (구체적이면 더 좋습니다.)
  - 참여율을 위해 난이도가 높은 주제보다는 팀원들이 모두 이해가 가능한 정도의 주제였으면 합니다.
## 논의 마감
- 11월 12일 (화) 23:59 까지
### 팀 과제 안내: 다음 내용과 디자인, 팀원들의 협업 활동을 함께 평가[^1]
- 내용과 함께 깃허브의 다양한 기능 사용 평가
  - 이슈, 마일스톤, 레이블, PR, 위키, 프로젝트 등
- 팀(수업의 같은 반 4-7명) 별 GitHub 저장소 구축
  - 내용 파일은.md 파일로 작성
  - 팀원의 활동이 축적
- 팀 과제 주소 업로드
  - [A반](https://docs.google.com/spreadsheets/d/1h9_Mlgt9wpgLoEXxeexH0rVLXnje0cYH-NCQoqE1eXg/edit?usp=sharing)
  - [B반](https://docs.google.com/spreadsheets/d/1N_nsCXXCHMTXm5z-7ULzgeUfiKECTVSyBsfPgSHF98I/edit?usp=sharing)
- 과제 마감일
  - 2024.12.06(금)
> - 사례1: 오픈소스소프트웨어 보고서 구축
>   - OSS 개요, OSS 역사
>   - 대표적 OSS 소개
>   - OSS 저작권
> - 사례2: 실제 소프트웨어 개발 구축
>   - ChatGPT로 최초 소프트웨어를 생성
>   - 팀원들이 더욱 개선해 나가는 협업 과정(커밋이 여러 번 발생)

[^1]: https://github.com/ai7dnn/2024-OSS

**Comment by pcw11** [comment]
오픈소스 소프트웨어 사용 사례나 장단점 혹은 웹이나 앱에서 하나를 벤치마킹해서 소프트웨어 개발 구축하는 방법?

**Comment by sjunc** [comment]
이번 학기에 배우고 있는 자바, 웹서버, 데이터베이스를 활용한 웹페이지 제작해보기 가 좋을 것 같습니다.

**Comment by MoonHwitae** [comment]
오픈소스 속 내용들을 활용해서 간단한 명령어들로 HTML웹사이트 같은 것 들을 만들 때 어떤 구조로 짜야 하는지,어떤 부분을 가장 조심하고 만들어야 하는지 등 편리하게 구조 작업하는 방법에 대해서 하는 것이 좋다고 생각합니다

**Comment by jungsh20241509** [comment]
오픈소스 소프트웨어가 보안에 미치는 영향과 취약점관리
이유:오픈소스는 누구나 코드에 접근을 할 수 있기 때문에 보안 취약점이 쉽게 발견될수 있지만 동시에 커뮤니티의 협력 덕분에 빠르게 패치 될수도 있습니다 이런 보안 관점에서 오픈소스의 장단점,취약점 관리 방안을 논의 해 보면 좋을것 같습니다
